# Dockerfile.consumer
FROM python:3.11

WORKDIR /app

COPY consumer-service/ .

COPY consumer-service/requirements.txt .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

CMD ["python", "main.py"]
